config/routes.rb
Rails.application.routes.draw do

  root "users#home"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  get 'index', to: 'admin#index', as: 'admin_index'

  resources :users do
    get 'dashboard', on: :collection
  end
  resources :sessions
  resources :books
  resources :members
  resources :book_issues
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_issues
end

app/models/book_issue.rb
class BookIssue < ApplicationRecord
  belongs_to :book
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :book_issues
end

app/models/user.rb
class User < ApplicationRecord
  has_many :book_issues
  has_secure_password
  #attr_accessor :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @admins = User.where(role: "admin")
  end

  def dashboard
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def authorize
		redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end
end

app/controllers/book_issues_controller.rb
class BookIssuesController < ApplicationController

  def index
    @book_issues = BookIssue.all         
  end


  def new
    @book_issue = BookIssue.new()
  end

  def create
    @book_issue = BookIssue.create(modify_params)
    if @book_issue.save!
      redirect_to book_issues_path
    else
      render new
    end
  end

  def edit
    @book_issue = BookIssue.find(params[:id])
  end

  def update
    @book_issue = BookIssue.find(params[:id])
    if @book_issue.update(modify_params)
      redirect_to book_issues_path
    else
      render 'edit'
    end
  end

  def modify_params
    user_id = book_issue_params[:user_id]
    book_id = book_issue_params[:book_id]
    user_first_name = User.find(user_id).first_name
    user_last_name = User.find(user_id).last_name
    user_name = user_first_name +" "+ user_last_name
    book_name = Book.find(book_id).name

    modify = {book_name: book_name, user_name: user_name}

    book_issue_params.merge!(modify)
  end
  
  private

  def book_issue_params
    params.require(:book_issue).permit(:user_id, :book_id, :issue_date)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_forgery_protection
  def index
    @books = Book.all
  end

  def show
    # books = Book.find(params[:id])
  end

  def new
    @book = Book.new()
  end

  def create
    @book = Book.create(book_params)
    if @book.save!
      redirect_to books_path
    else
      render new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :genr, :isbn, :availability, :item_count)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to members_path
    else
      render new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to members_path
    else
      render 'edit'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to members_path
  end

  private

  def member_params
    params.require(:member).permit(:name, :email, :mobile_no)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      #redirect_to root_url, notice: "Logged in!"
      if user.role == "admin"
        redirect_to admin_dashboard_path
      else
        redirect_to dashboard_users_path
      end
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.where(role: "user")
	end

  def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end
	
	def dashboard
    # Additional logic for the dashboard action if needed
  end
	
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			if @user.role == "admin"
        redirect_to admin_dashboard_path
      else
        redirect_to dashboard_users_path
      end
		else
			render "new"
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			if @user.role == "admin"
				redirect_to admin_index_path
			elsif current_user == @user
				redirect_to user_path
			else
				redirect_to users_path
			end
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :role, :date_of_birth)
	end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_issues_helper.rb
module BookIssuesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<h1> Welcom to Admin page </h1>

<div style="display: inline-block;">
  <%= button_to "View Books", books_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
	<%= button_to "Show Admins list", admin_index_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
	<%= button_to "Show Users list", users_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
	<%= button_to "Issue Book", new_book_issue_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
  <%= button_to "Issued Book", book_issues_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
</div>

app/views/admin/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>


<h1>Admin Data</h1>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th>Date_of_birth</th>
    <th>Action</th>
  </tr>
  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.first_name%></td>
      <td><%= admin.last_name%></td>
      <td><%= admin.email %></td>
      <td><%= admin.phone_number %></td>
      <td><%= admin.date_of_birth %></td>
      <td>
				<% if current_user.email == admin.email %>
					<div style="display: inline-block;">
						<%= button_to "Edit Admin", edit_user_path(admin), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
					</div>
					<div style="display: inline-block;">
						<%= button_to "Delete Admin", user_path(admin), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-danger border-0 rounded-pill shadow p-2 m-2", style: "background-color: #FFB6C1;" %>
					</div>
				<% end %>
			</td>
    </tr>
  <% end %>
</table>

app/views/book_issues/_book_issue.html.erb
<div id="<%= dom_id book_issue %>">
  <p>
    <strong>Book:</strong>
    <%= book_issue.book_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= book_issue.user_id %>
  </p>

  <p>
    <strong>Issue date:</strong>
    <%= book_issue.issue_date %>
  </p>

</div>

app/views/book_issues/_form.html.erb
<%= form_with(model: book_issue) do |form| %>
  <% if book_issue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_issue.errors.count, "error") %> prohibited this book_issue from being saved:</h2>

      <ul>
        <% book_issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :issue_date, style: "display: block" %>
    <%= form.text_field :issue_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_issues/edit.html.erb
<h1>Editing book issue</h1>

<%= render "form", book_issue: @book_issue %>

<br>

<div>
  <%= link_to "Show this book issue", @book_issue %> |
  <%= link_to "Back to book issues", book_issues_path %>
</div>

app/views/book_issues/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>


<h1>Issued Book</h1>
<table>
  <tr>
    <th>Book Id</th>
    <th>Book Name</th>
    <th>User Id</th>
    <th>User Name</th>
    <th>Issue Date</th>
  </tr>
  <% @book_issues.each do |issue_book| %>
    <tr>
      <td><%= issue_book.book_id%></td>
      <td><%= issue_book.book_name%></td>
      <td><%= issue_book.user_id%></td>
      <td><%= issue_book.user_name%></td>
      <td><%= issue_book.issue_date %></td>
    </tr>
  <% end %>
</table>

app/views/book_issues/new.html.erb
<style>
  .form-container {
    width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #f9f9f9;
  }

  label {
    font-weight: bold;
  }

  /* Style for form input fields */
  input[type="text"] {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type="submit"] {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  /* Hover effect for submit button */
  input[type="submit"]:hover {
    background-color: #45a049;
  }
</style>

<div class="form-container">
  <h2>Issue Book</h2>
  <%= form_with model: @book_issue do |form| %>
    <div>
      <%= form.label :BOOK_ID %><br>
      <%= form.text_field :book_id %>
    </div>

    <div>
      <%= form.label :USER_ID %><br>
      <%= form.text_field :user_id %>
    </div>

    <div>
      <%= form.label :ISSUE_DATE %><br>
      <%= form.date_field :issue_date %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/book_issues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_issue %>

<div>
  <%= link_to "Edit this book issue", edit_book_issue_path(@book_issue) %> |
  <%= link_to "Back to book issues", book_issues_path %>

  <%= button_to "Destroy this book issue", @book_issue, method: :delete %>
</div>

app/views/books/edit.html.erb
<style>
	.form-container {
		width: 400px;
		margin: 0 auto;
		padding: 20px;
		border: 1px solid #ccc;
		border-radius: 5px;
		background-color: #f9f9f9;
	}

	label {
    font-weight: bold;
  }

	input[type="text"] {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

	input[type="submit"] {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

	input[type="submit"]:hover {
    background-color: blue;
  }

</style>

<div class="form-container">
	<h2>Edit book</h2>

	
	<div>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :Author %><br>
		<%= form.text_field :author %>
	</div>

	<div>
		<%= form.label :genr %><br>
		<%= form.text_field :genr %>
	</div>

	<div>
		<%= form.label :Isbn %><br>
		<%= form.text_field :isbn %>
	</div>

	<div>
		<%= form.label :availability %><br>
		<%= form.text_field :availability %>
	</div>

	<div>
		<%= form.label :count %><br>
		<%= form.text_field :item_count %>
	</div>


	<form action="#" method="post">
		<div>
				<button type="submit">Submit</button>
		</div>
	</form>

</div>

app/views/books/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<h1>Books</h1>
<% if current_user.role == "admin" %>
	<table>
		<tr>
			<th>SI no</th>
			<th>Book_id</th>
			<th>Name</th>
			<th>Author</th>
			<th>Genr</th>
			<th>ISBN</th>
			<th>Availability</th>
			<th>Quantity</th>
			<th>Action</th>
		</tr>

		<% @books.each_with_index do |book, index| %>
			<tr>
				<td><%= index + 1%></td>
				<td><%= book.id %></td>
				<td><%= book.name %></td>
				<td><%= book.author %></td>
				<td><%= book.genr %></td>
				<td><%= book.isbn %></td>
				<td><%= book.availability ? 'Available' : 'Not Available' %></td>
				<td><%= book.item_count%></td>
				<td>
				<div style="display: inline-block;">
					<%= button_to "Edit Book", edit_book_path(book), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
				</div>
				<div style="display: inline-block;">
					<%= button_to "Delete Book", book_path(book), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-danger border-0 rounded-pill shadow p-2 m-2", style: "background-color: #FFB6C1;" %>
				</div>
				</td>
			</tr>
		<% end %>
	</table>

	<div class="d-flex">
			<%= button_to "Add New Book", new_book_path, method: :get, class:"btn-warning border-0 rounded-pill shadow p-4 m-4", style: "background-color: green;" %>
	</div>
<% else %>
	<table>
		<tr>
			<th>SI no</th>
			<th>Name</th>
			<th>Author</th>
			<th>Genr</th>
			<th>ISBN</th>
			<th>Availability</th>
			<th>Quantity</th>
		</tr>

		<% @books.each_with_index do |book, index| %>
			<tr>
				<td><%= index + 1%></td>
				<td><%= book.name %></td>
				<td><%= book.author %></td>
				<td><%= book.genr %></td>
				<td><%= book.isbn %></td>
				<td><%= book.availability ? 'Available' : 'Not Available' %></td>
				<td><%= book.item_count%></td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/books/new.html.erb
<style>
  .form-container {
    width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #f9f9f9;
  }

  label {
    font-weight: bold;
  }

  /* Style for form input fields */
  input[type="text"] {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type="submit"] {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  /* Hover effect for submit button */
  input[type="submit"]:hover {
    background-color: #45a049;
  }
</style>

<div class="form-container">
  <h2>Add New Book</h2>
  <%= form_with model: @book do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :Author %><br>
      <%= form.text_field :author %>
    </div>

    <div>
      <%= form.label :genr %><br>
      <%= form.text_field :genr %>
    </div>

    <div>
      <%= form.label :Isbn %><br>
      <%= form.text_field :isbn %>
    </div>

    <div>
      <%= form.label :Availability %><br>
      <%= form.text_field :availability %>
    </div>

    <div>
      <%= form.label :Quantity %><br>
      <%= form.text_field :item_count %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Library Management System</a>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
    <%end%>
  </body>
</html>

app/views/members/edit.html.erb
<h2>Update Member</h2>

<%= form_with model: @member do |form| %>
	<div>
		<%= form.label :Name %><br>
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :Email %><br>
		<%= form.text_field :email %>
	</div>

	<div>
		<%= form.label :Mobile_no %><br>
		<%= form.text_field :mobile_no %>
	</div>

	<div>
    <%= form.submit %>
  </div>
<%end%>

app/views/members/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>


<h1>Members</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile_no</th>
    <th>Action</th>
  </tr>
  <% @members.each do |member| %>
    <tr>
      <td><%= member.name %></td>
      <td><%= member.email %></td>
      <td><%= member.mobile_no %></td>
      <td>
  			<div style="display: inline-block;">
    			<%= button_to "Edit Member", edit_member_path(member), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
  			</div>
  			<div style="display: inline-block;">
    			<%= button_to "Delete Member", member_path(member), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-danger border-0 rounded-pill shadow p-2 m-2", style: "background-color: #FFB6C1;" %>
  			</div>
			</td>
    </tr>
  <% end %>
</table>

<div class="d-flex">
    <%= button_to "Add New Member", new_member_path, method: :get, class:"btn-warning border-0 rounded-pill shadow p-3 m-3", style: "background-color: green;" %>
</div>

app/views/members/new.html.erb
<h2>Add new Member</h2>

<%= form_with model: @member do |form| %>
	<div>
		<%= form.label :Name %><br>
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :Email %><br>
		<%= form.text_field :email %>
	</div>

	<div>
		<%= form.label :Mobile_no %><br>
		<%= form.text_field :mobile_no %>
	</div>

	<div>
    <%= form.submit %>
  </div>
<%end%>

app/views/users/dashboard.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<h1> Welcom to User dashboard </h1>

<div style="display: inline-block;">
  <%= button_to "View Books", books_path, method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
	<%= button_to "My Book", class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
	<%= button_to "Profile", user_path(current_user), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
</div>

app/views/users/home.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<h1>Welcome to Our Library</h1>
<div style="display: inline-block;">

	<div style="display: inline-block;">
		<%= button_to "Sign Up", signup_path, method: :get, class:"btn-success border-0 shadow p-2 m-2", style: "background-color: #87CEEB;" %>
	</div>
	<div style="display: inline-block;">
		<%= button_to "Log In", login_path, method: :get, class:"btn-success border-0 shadow p-2 m-2", style: "background-color: #FF00FF;" %>
	</div>
</div>

app/views/users/index.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>


<h1>Users Data</h1>
<table>
  <tr>
    <th>User Id</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th>Role</th>
    <th>Action</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name%></td>
      <td><%= user.last_name%></td>
      <td><%= user.email %></td>
      <td><%= user.phone_number %></td>
      <td><%= user.role %></td>
      <td>
        <div style="display: inline-block;">
          <%= button_to "Edit User", edit_user_path(user), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
        </div>
        <div style="display: inline-block;">
          <%= button_to "Delete user", user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn-danger border-0 rounded-pill shadow p-2 m-2", style: "background-color: #FFB6C1;" %>
        </div>
		</td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>


<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th>Date_of_birth</th>
    <th>Action</th>
  </tr>
	<tr>
		<td><%= @user.first_name%></td>
		<td><%= @user.last_name%></td>
		<td><%= @user.email %></td>
		<td><%= @user.phone_number %></td>
		<td><%= @user.date_of_birth %></td>
		<td>
			<div style="display: inline-block;">
				<%= button_to "Edit User", edit_user_path(@user), method: :get, class:"btn-success border-0 rounded-pill shadow p-2 m-2", style: "background-color: yellow;" %>
			</div>
		</td>
	</tr>
</table>